def sapa():
    nama = input("Masukkan nama kamu : ")
    print("HAI SALAM KENAL", nama)

def ucapan(nama2):
    print("Selamat Sore", nama2)

def hitung(angka1, angka2):
    print("selamat menghitung")
    return angka1+angka2                                                                                                                                                                                                                                                                                                                    
sapa()
ucapan("Tiyo")
hitung()